language: python
python:
  - "3.5"

services:
  - docker

install:
  - docker build -t grafcli-dev -f tests/integration/Dockerfile .
  - docker run -d -p 3000:3000 --name grafana grafana/grafana

script:
  - docker run -v $TRAVIS_BUILD_DIR:/app grafcli-dev unittests
  - docker run --link grafana -v $TRAVIS_BUILD_DIR:/app grafcli-dev integration
